name: Build styleguide

on:
    push:
        branches:
            - master
    release:
        types:
            - released

jobs:
    build-styleguide:
        name: Build styleguide
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v1

            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

            - name: Print the version
              run: echo Version ${{ steps.get_version.outputs.VERSION }}

            - name: Print github tagname
              run: echo ${{ github.event.release.tag_name }}


            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump job context
              env:
                  JOB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"
            - name: Dump steps context
              env:
                  STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"
            - name: Dump runner context
              env:
                  RUNNER_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
            - name: Dump strategy context
              env:
                  STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              run: echo "$STRATEGY_CONTEXT"
            - name: Dump matrix context
              env:
                  MATRIX_CONTEXT: ${{ toJson(matrix) }}
              run: echo "$MATRIX_CONTEXT"

#            - name: Use Node.js 12
#              uses: actions/setup-node@v1
#              with:
#                  node-version: 12.x
#
#            - name: Install dependencies
#              run: npm install
#
#            - name: Clone SuluJsReference repository
#              run: git clone git@github.com:luca-rath/sulu-js-reference.git styleguide
#
#            - name: Build styleguide
#              run: npm run styleguide:build
