name: Build styleguide

on:
    push:
        branches:
            - master
    release:
        types:
            - released

jobs:
    build-styleguide:
        name: Build styleguide
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v1

            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

            - name: Print the version
              run: echo Version ${{ steps.get_version.outputs.VERSION }}

            - name: Print github tagname
              run: echo ${{ github.event }}

#            - name: Use Node.js 12
#              uses: actions/setup-node@v1
#              with:
#                  node-version: 12.x
#
#            - name: Install dependencies
#              run: npm install
#
#            - name: Clone SuluJsReference repository
#              run: git clone git@github.com:luca-rath/sulu-js-reference.git styleguide
#
#            - name: Build styleguide
#              run: npm run styleguide:build
